version: 1.0.{build}

image: Visual Studio 2019

configuration: Release
platform: x64

build:
  project: DarkId.Papyrus.DebugServer.sln
  verbosity: minimal

install:
  - if not exist c:\tools\vcpkg mkdir c:\tools\vcpkg
  - cd c:\tools\vcpkg
  - rm -rf .git
  - git init
  - git remote add origin https://github.com/microsoft/vcpkg
  - git fetch
  - git branch master origin/master
  - git checkout master
  - .\bootstrap-vcpkg.bat
  - vcpkg install websocketpp:x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - c:\tools\vcpkg\installed -> .appveyor.yml