version: 1.0.{build}

image: Visual Studio 2019

configuration: Release
platform: x64

build:
  project: DarkId.Papyrus.DebugServer.sln
  verbosity: minimal

install:
  - cd c:\tools
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - .\bootstrap-vcpkg.bat
  - vcpkg install fruit:x64-windows websocketpp:x64-windows jsoncpp:x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - c:\tools\vcpkg\installed