version: 1.0.0.{build}

image: Visual Studio 2019

configuration: Release
platform: x64

environment:
  WEBHOOK_URL:
    secure: Oyrlvti3D7Zf0SDrYnP5AprH1IDT0upe+oy39EGEZP6vYDg5/NjESFLiLRLO1EMamTVCqIfhxkqWWKq3o1RIlqPT7Kib+uvcI+DHD+OqTZHz3FIWAQhIZWcg0li0QOEnlK9YTjT5f2GWzIgtgJnV793iejlUMnDYBRKZxCewmSU=

build:
  project: DarkId.Papyrus.DebugServer.sln
  verbosity: minimal

install:
  - if not exist c:\tools\vcpkg mkdir c:\tools\vcpkg
  - cd c:\tools\vcpkg
  - rm -rf .git
  - git init
  - git remote add origin https://github.com/microsoft/vcpkg
  - git fetch
  - git branch master origin/master
  - git checkout master
  - .\bootstrap-vcpkg.bat
  - vcpkg install websocketpp:x64-windows
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - c:\tools\vcpkg\installed

artifacts:
  - path: bin/x64/Release/DarkId.Papyrus.DebugServer.dll

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL